-- UniService: ampliación de la base existente. PostgreSQL / Supabase.
-- Ejecutar UNA VEZ después de checks/00_inventario.sql. No crea ni borra usuarios.
BEGIN;

DO $$
BEGIN
  IF to_regclass('public.usuarios') IS NULL THEN
    RAISE EXCEPTION 'Falta public.usuarios. Esta migración no reconstruye la base original.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'usuarios'
      AND column_name = 'id_usuario' AND data_type = 'integer') THEN
    RAISE EXCEPTION 'Se requiere usuarios.id_usuario de tipo integer. Revisar inventario.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public'
      AND table_name = 'usuarios' AND column_name = 'estado' AND data_type = 'boolean') THEN
    RAISE EXCEPTION 'Se requiere usuarios.estado boolean.';
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS uniservice_mobile;
REVOKE ALL ON SCHEMA uniservice_mobile FROM PUBLIC, anon, authenticated;
CREATE TABLE uniservice_mobile.migraciones (
  version text PRIMARY KEY,
  aplicada_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.identidades_institucionales (
  id_usuario integer PRIMARY KEY REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  tenant_id uuid NOT NULL,
  object_id uuid NOT NULL,
  verificado_en timestamptz NOT NULL DEFAULT now(),
  verificado_hasta timestamptz NOT NULL,
  UNIQUE (tenant_id, object_id),
  CHECK (verificado_hasta > verificado_en),
  CHECK (tenant_id <> '00000000-0000-0000-0000-000000000000'::uuid),
  CHECK (object_id <> '00000000-0000-0000-0000-000000000000'::uuid)
);
COMMENT ON TABLE public.identidades_institucionales IS
  'Sólo el servidor escribe después de validar Microsoft y el rol académico. No es una autodeclaración del cliente.';

CREATE TABLE public.habilidades (
  id_habilidad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL CHECK (length(trim(nombre)) BETWEEN 2 AND 80),
  activa boolean NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX ux_habilidades_nombre ON public.habilidades(lower(trim(nombre)));

CREATE TABLE public.usuario_habilidades (
  id_usuario integer NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  id_habilidad integer NOT NULL REFERENCES public.habilidades(id_habilidad),
  nivel varchar(20) NOT NULL CHECK (nivel IN ('basico', 'intermedio', 'avanzado')),
  detalle varchar(500) NOT NULL DEFAULT '',
  PRIMARY KEY (id_usuario, id_habilidad)
);
CREATE INDEX ix_usuario_habilidades_matching ON public.usuario_habilidades(id_habilidad, id_usuario);

-- Complemento del perfil. Estos datos son declarados por el usuario, no prueban matrícula.
CREATE TABLE public.perfiles_academicos (
  id_usuario integer PRIMARY KEY REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  programa varchar(120) NOT NULL DEFAULT '',
  semestre smallint CHECK (semestre BETWEEN 1 AND 20),
  sede varchar(120) NOT NULL DEFAULT '',
  disponibilidad varchar(500) NOT NULL DEFAULT '',
  portafolio_url varchar(500) CHECK (portafolio_url ~ '^https://[^[:space:]]+$'),
  actualizado_en timestamptz NOT NULL DEFAULT now()
);

-- Petición abierta de ayuda: diferente de solicitudes (contratación de un servicio existente).
CREATE TABLE public.peticiones_servicio (
  id_peticion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_autor integer NOT NULL REFERENCES public.usuarios(id_usuario),
  titulo varchar(120) NOT NULL CHECK (length(trim(titulo)) BETWEEN 5 AND 120),
  descripcion varchar(4000) NOT NULL CHECK (length(trim(descripcion)) BETWEEN 20 AND 4000),
  presupuesto numeric(12,2) CHECK (presupuesto >= 0),
  modalidad varchar(20) NOT NULL CHECK (modalidad IN ('virtual', 'presencial', 'mixta')),
  fecha_limite timestamptz NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'abierta'
    CHECK (estado IN ('abierta', 'asignada', 'completada', 'cancelada')),
  creado_en timestamptz NOT NULL DEFAULT now(),
  CHECK (fecha_limite > creado_en AND fecha_limite <= creado_en + interval '90 days')
);
CREATE INDEX ix_peticiones_feed ON public.peticiones_servicio(estado, fecha_limite, creado_en DESC);
CREATE INDEX ix_peticiones_autor ON public.peticiones_servicio(id_autor, creado_en DESC);

CREATE TABLE public.peticion_habilidades (
  id_peticion integer NOT NULL REFERENCES public.peticiones_servicio(id_peticion) ON DELETE CASCADE,
  id_habilidad integer NOT NULL REFERENCES public.habilidades(id_habilidad),
  PRIMARY KEY (id_peticion, id_habilidad)
);
CREATE INDEX ix_peticion_habilidades_matching ON public.peticion_habilidades(id_habilidad, id_peticion);

CREATE TABLE public.postulaciones_servicio (
  id_postulacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_peticion integer NOT NULL REFERENCES public.peticiones_servicio(id_peticion) ON DELETE CASCADE,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id_usuario),
  mensaje varchar(2000) NOT NULL CHECK (length(trim(mensaje)) BETWEEN 10 AND 2000),
  precio_propuesto numeric(12,2) CHECK (precio_propuesto >= 0),
  estado varchar(20) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aceptada', 'rechazada')),
  creado_en timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_peticion, id_usuario)
);
CREATE UNIQUE INDEX ux_postulacion_aceptada ON public.postulaciones_servicio(id_peticion) WHERE estado = 'aceptada';
CREATE INDEX ix_postulaciones_usuario ON public.postulaciones_servicio(id_usuario, creado_en DESC);

-- La identidad actual es integer + JWT de .NET; no equivale a auth.uid() de Supabase.
-- Acceso a estas tablas exclusivamente desde servidor, nunca desde Flutter con service_role.
ALTER TABLE public.identidades_institucionales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.habilidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario_habilidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles_academicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.peticiones_servicio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.peticion_habilidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.postulaciones_servicio ENABLE ROW LEVEL SECURITY;
ALTER TABLE uniservice_mobile.migraciones ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.identidades_institucionales, public.habilidades, public.usuario_habilidades,
  public.perfiles_academicos, public.peticiones_servicio, public.peticion_habilidades,
  public.postulaciones_servicio, uniservice_mobile.migraciones FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.habilidades_id_habilidad_seq,
  public.peticiones_servicio_id_peticion_seq, public.postulaciones_servicio_id_postulacion_seq
  FROM PUBLIC, anon, authenticated;
-- El propietario de las tablas (.NET con conexión PostgreSQL de servidor) conserva su acceso.

INSERT INTO public.habilidades(nombre) VALUES
  ('Programación'), ('Flutter'), ('Diseño gráfico'), ('Matemáticas'), ('Inglés'),
  ('Redacción'), ('Fotografía'), ('Reparación de computadores'), ('Contabilidad'), ('Edición de video');

INSERT INTO uniservice_mobile.migraciones(version) VALUES ('001_bolsa_y_perfiles');
COMMIT;
