import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

// Base desechable en memoria. No lee variables ni credenciales de Supabase.
const db = new PGlite();
let assertions = 0;
async function ok(sql, values = []) { return (await db.query(sql, values)).rows; }
function check(condition, message) { assert.ok(condition, message); assertions++; }
async function rejects(sql, code, values = []) {
  try { await db.query(sql, values); }
  catch (error) { assert.equal(error.code, code, error.message); assertions++; return; }
  assert.fail(`Se esperaba rechazo ${code}: ${sql}`);
}
async function migration(name) {
  await db.exec(await readFile(new URL(`../migrations/${name}`, import.meta.url), 'utf8'));
}

try {
  await db.exec(`
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE TABLE public.usuarios (
      id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre varchar(50) NOT NULL, correo varchar(100) NOT NULL UNIQUE,
      estado boolean NOT NULL DEFAULT true, id_rol integer NOT NULL DEFAULT 2
    );
    INSERT INTO public.usuarios(id_usuario, nombre, correo, estado) VALUES
      (1, 'Autora', 'autora@unicesar.edu.co', true),
      (2, 'Candidato', 'candidato@unicesar.edu.co', true),
      (3, 'Sin coincidencias', 'otro@unicesar.edu.co', true),
      (4, 'Suspendido', 'suspendido@unicesar.edu.co', false),
      (5, 'Cuenta antigua', 'antigua@example.com', true),
      (6, 'Expirado', 'expirado@unicesar.edu.co', true),
      (7, 'Otro candidato', 'candidato2@unicesar.edu.co', true);
  `);
  await migration('001_bolsa_y_perfiles.sql');
  await migration('002_operaciones_servidor.sql');
  check((await ok('SELECT count(*)::integer AS n FROM usuarios'))[0].n === 7, 'Preservar cuentas antiguas');
  await db.exec(`
    INSERT INTO identidades_institucionales(id_usuario, tenant_id, object_id, verificado_en, verificado_hasta)
    SELECT id_usuario, '11111111-1111-1111-1111-111111111111'::uuid,
      ('22222222-2222-2222-2222-' || lpad(id_usuario::text, 12, '0'))::uuid,
      now() - interval '2 hours', CASE WHEN id_usuario = 6 THEN now() - interval '1 hour' ELSE now() + interval '1 hour' END
    FROM usuarios WHERE id_usuario <> 5;
  `);
  const flutter = (await ok("SELECT id_habilidad FROM habilidades WHERE nombre='Flutter'"))[0].id_habilidad;
  const maths = (await ok("SELECT id_habilidad FROM habilidades WHERE nombre='Matemáticas'"))[0].id_habilidad;
  const skill = [{ id_habilidad: flutter, nivel: 'intermedio', detalle: 'Apps móviles' }];
  for (const user of [2, 7]) await ok('SELECT uniservice_mobile.guardar_habilidades($1,$2::jsonb)', [user, JSON.stringify(skill)]);
  await ok('SELECT uniservice_mobile.guardar_habilidades(3,$1::jsonb)', [JSON.stringify([{ id_habilidad: maths, nivel: 'avanzado' }])]);
  await rejects('SELECT uniservice_mobile.guardar_habilidades(2,$1::jsonb)', '22023', [JSON.stringify([skill[0], skill[0]])]);
  check((await ok('SELECT count(*)::integer AS n FROM usuario_habilidades WHERE id_usuario=2'))[0].n === 1, 'Reemplazo inválido no borra perfil');
  await rejects('SELECT uniservice_mobile.guardar_habilidades(4,$1::jsonb)', '42501', [JSON.stringify(skill)]);
  await rejects('SELECT uniservice_mobile.guardar_habilidades(5,$1::jsonb)', '42501', [JSON.stringify(skill)]);
  await rejects('SELECT uniservice_mobile.guardar_habilidades(6,$1::jsonb)', '42501', [JSON.stringify(skill)]);
  await rejects("SELECT uniservice_mobile.guardar_habilidades(2,'{}'::jsonb)", '22023');
  await rejects('SELECT uniservice_mobile.crear_peticion(1,$1,$2,50000,$3,now()+interval \'7 days\',$4)', '22023',
    ['Petición inválida', 'Esta descripción cumple la longitud requerida.', 'virtual', []]);
  const petition = (await ok(`SELECT uniservice_mobile.crear_peticion(1,$1,$2,50000,'virtual',now()+interval '7 days',$3) AS id`,
    ['Necesito apoyo en Flutter', 'Quiero revisar una pantalla y conectar su formulario a una API.', [flutter]]))[0].id;
  const feed = 'SELECT * FROM uniservice_mobile.obtener_peticiones($1,$2,$3,1,20)';
  check((await ok(feed, [2, true, false])).length === 1, 'Habilidad relacionada recomienda petición');
  check((await ok(feed, [3, true, false])).length === 0, 'Sin coincidencia no recomienda');
  check((await ok(feed, [3, false, false])).length === 1, 'Exploración muestra abiertas');
  check((await ok(feed, [1, true, true])).length === 1, 'Autor ve propias');
  check((await ok(feed, [1, false, false])).length === 0, 'Feed de candidatos excluye propias');
  await rejects('SELECT * FROM uniservice_mobile.obtener_peticiones(2,true,false,0,20)', '22023');
  await rejects('SELECT * FROM uniservice_mobile.obtener_peticiones(2,true,false,1,51)', '22023');
  await rejects('SELECT uniservice_mobile.postular(1,$1,$2,NULL)', '22023', [petition, 'Propuesta del autor inválida']);
  await rejects('SELECT uniservice_mobile.postular(3,$1,$2,NULL)', '22023', [petition, 'Propuesta sin habilidad relacionada']);
  const proposal = (await ok('SELECT uniservice_mobile.postular(2,$1,$2,40000) AS id', [petition, 'Puedo ayudarte a revisar y conectar la pantalla.']))[0].id;
  await rejects('SELECT uniservice_mobile.postular(2,$1,$2,NULL)', '23505', [petition, 'Segunda propuesta repetida']);
  await ok('SELECT uniservice_mobile.postular(7,$1,$2,45000)', [petition, 'También puedo ayudarte con tu proyecto.']);
  check((await ok('SELECT * FROM uniservice_mobile.obtener_postulaciones(1,$1)', [petition])).length === 2, 'Autor ve candidatos');
  check((await ok('SELECT * FROM uniservice_mobile.obtener_postulaciones(2,$1)', [petition])).length === 1, 'Candidato ve sólo su propuesta');
  check((await ok('SELECT * FROM uniservice_mobile.obtener_postulaciones(3,$1)', [petition])).length === 0, 'Tercero no ve propuestas');
  await rejects('SELECT uniservice_mobile.aceptar_postulacion(3,$1,$2)', '42501', [petition, proposal]);
  await rejects("SELECT uniservice_mobile.cambiar_estado(1,$1,'completada')", '22023', [petition]);
  check((await ok('SELECT uniservice_mobile.aceptar_postulacion(1,$1,$2) AS proveedor', [petition, proposal]))[0].proveedor === 2, 'Aceptación devuelve candidato');
  check((await ok("SELECT count(*)::integer AS n FROM postulaciones_servicio WHERE estado='aceptada'"))[0].n === 1, 'Un candidato aceptado');
  check((await ok("SELECT count(*)::integer AS n FROM postulaciones_servicio WHERE estado='rechazada'"))[0].n === 1, 'Rechaza demás candidatos');
  await rejects('SELECT uniservice_mobile.aceptar_postulacion(1,$1,$2)', '22023', [petition, proposal]);
  await rejects('SELECT uniservice_mobile.postular(3,$1,$2,NULL)', '22023', [petition, 'Propuesta después de asignar']);
  await ok("SELECT uniservice_mobile.cambiar_estado(1,$1,'completada')", [petition]);
  await rejects("SELECT uniservice_mobile.cambiar_estado(1,$1,'cancelada')", '22023', [petition]);
  const cancelled = (await ok(`SELECT uniservice_mobile.crear_peticion(1,'Una petición cancelable','Descripción suficiente para probar la cancelación.',NULL,'mixta',now()+interval '1 day',$1) AS id`, [[flutter]]))[0].id;
  await ok('SELECT uniservice_mobile.postular(2,$1,$2,NULL)', [cancelled, 'Propuesta antes de cancelar']);
  await ok("SELECT uniservice_mobile.cambiar_estado(1,$1,'cancelada')", [cancelled]);
  check((await ok('SELECT estado FROM postulaciones_servicio WHERE id_peticion=$1', [cancelled]))[0].estado === 'rechazada', 'Cancelación rechaza propuestas');
  await rejects('SELECT uniservice_mobile.postular(7,$1,$2,NULL)', '22023', [cancelled, 'Propuesta posterior a cancelar']);
  await rejects("INSERT INTO perfiles_academicos(id_usuario,portafolio_url) VALUES(2,'http://example.com')", '23514');
  await rejects(`SELECT uniservice_mobile.crear_peticion(1,'Fecha inválida','Esta descripción cumple los requisitos mínimos.',NULL,'virtual',now()-interval '1 hour',$1)`, '23514', [[flutter]]);
  await rejects(`SELECT uniservice_mobile.crear_peticion(1,'Precio inválido','Esta descripción cumple los requisitos mínimos.',-1,'virtual',now()+interval '1 day',$1)`, '23514', [[flutter]]);
  await rejects(`SELECT uniservice_mobile.crear_peticion(1,'Habilidad duplicada','Esta descripción cumple los requisitos mínimos.',NULL,'virtual',now()+interval '1 day',$1)`, '22023', [[flutter, flutter]]);
  const expiredPetition = (await ok(`SELECT uniservice_mobile.crear_peticion(1,'Petición que vence','Esta descripción cumple los requisitos mínimos.',NULL,'virtual',now()+interval '1 day',$1) AS id`, [[flutter]]))[0].id;
  await ok("UPDATE peticiones_servicio SET creado_en=now()-interval '2 days', fecha_limite=now()-interval '1 day' WHERE id_peticion=$1", [expiredPetition]);
  check((await ok(feed, [2, true, false])).length === 0, 'El feed excluye peticiones vencidas y completadas/canceladas');
  await rejects('SELECT uniservice_mobile.postular(2,$1,$2,NULL)', '22023', [expiredPetition, 'No se admite por plazo vencido']);
  // El índice evita un segundo ganador aun en escritura directa del servidor.
  const assigned = (await ok(`SELECT uniservice_mobile.crear_peticion(1,'Prueba de índice único','Esta descripción cumple los requisitos mínimos.',NULL,'virtual',now()+interval '1 day',$1) AS id`, [[flutter]]))[0].id;
  await ok('SELECT uniservice_mobile.postular(2,$1,$2,NULL)', [assigned, 'Primera propuesta para probar índice']);
  await ok('SELECT uniservice_mobile.postular(7,$1,$2,NULL)', [assigned, 'Otra propuesta para probar índice']);
  await ok("UPDATE postulaciones_servicio SET estado='aceptada' WHERE id_peticion=$1 AND id_usuario=2", [assigned]);
  await rejects("UPDATE postulaciones_servicio SET estado='aceptada' WHERE id_peticion=$1 AND id_usuario=7", '23505', [assigned]);

  // Los roles de cliente no acceden a ninguna operación sobre las tablas nuevas.
  const tables = ['identidades_institucionales', 'habilidades', 'usuario_habilidades', 'perfiles_academicos',
    'peticiones_servicio', 'peticion_habilidades', 'postulaciones_servicio'];
  for (const role of ['anon', 'authenticated']) {
    await db.exec(`SET ROLE ${role}`);
    try {
      for (const table of tables) {
        for (const sql of [`SELECT * FROM public.${table}`, `INSERT INTO public.${table} DEFAULT VALUES`,
          `UPDATE public.${table} SET ${table === 'habilidades' ? 'nombre=nombre' : 'id_usuario=id_usuario'}`, `DELETE FROM public.${table}`]) {
          // UPDATE necesita un nombre existente para verificar permiso, no un error de columna.
          const validSql = sql.replace('id_usuario=id_usuario',
            ['peticiones_servicio', 'peticion_habilidades'].includes(table) ? 'id_peticion=id_peticion' : 'id_usuario=id_usuario');
          await rejects(validSql, '42501');
        }
      }
      await rejects('SELECT uniservice_mobile.exigir_estudiante(1)', '42501');
    } finally { await db.exec('RESET ROLE'); }
  }
  const grants = await ok(`SELECT p.proname, p.prosecdef,
    has_function_privilege('anon',p.oid,'EXECUTE') AS anon,
    has_function_privilege('authenticated',p.oid,'EXECUTE') AS authenticated
    FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='uniservice_mobile'`);
  check(grants.every(row => !row.prosecdef && !row.anon && !row.authenticated), 'Funciones sólo de servidor sin SECURITY DEFINER');

  await migration('003_activar_registro_institucional.sql');
  check((await ok('SELECT count(*)::integer AS n FROM usuarios'))[0].n === 7, 'Activación conserva cuentas antiguas');
  await rejects("INSERT INTO usuarios(id_usuario,nombre,correo) VALUES(10,'Inválido','user@unicesar.edu.co.attacker.test')", '23514');
  await rejects("INSERT INTO usuarios(id_usuario,nombre,correo) VALUES(10,'Inválido','user@example.com')", '23514');
  await rejects("INSERT INTO usuarios(id_usuario,nombre,correo) VALUES(10,'Sin vínculo','nuevo@unicesar.edu.co')", '42501');
  check((await ok('SELECT count(*)::integer AS n FROM usuarios WHERE id_usuario=10'))[0].n === 0, 'Alta sin Microsoft se revierte');
  await db.exec(`BEGIN;
    INSERT INTO usuarios(id_usuario,nombre,correo) VALUES(10,'Nuevo Microsoft',' NUEVO@UNICESAR.EDU.CO ');
    INSERT INTO identidades_institucionales(id_usuario,tenant_id,object_id,verificado_hasta)
      VALUES(10,'11111111-1111-1111-1111-111111111111','22222222-2222-2222-2222-000000000010',now()+interval '1 hour');
    COMMIT;`);
  check((await ok('SELECT correo FROM usuarios WHERE id_usuario=10'))[0].correo === 'nuevo@unicesar.edu.co', 'Alta transaccional normaliza correo');
  await rejects("INSERT INTO usuarios(id_usuario,nombre,correo) VALUES(11,'Duplicado','NUEVO@unicesar.edu.co')", '23505');
  await rejects("UPDATE usuarios SET correo='otrocorreo@unicesar.edu.co' WHERE id_usuario=10", '42501');
  await ok("UPDATE usuarios SET nombre='Cuenta antigua preservada' WHERE id_usuario=5");
  check((await ok('SELECT correo FROM usuarios WHERE id_usuario=5'))[0].correo === 'antigua@example.com', 'Actualizar nombre legado no modifica correo');
  const ledger = await ok('SELECT version FROM uniservice_mobile.migraciones');
  check(ledger.length === 3, 'Tres migraciones registradas');
  console.log(`PASS: ${assertions} comprobaciones SQL en PostgreSQL/PGlite; sin conexión remota.`);
} finally {
  await db.close();
}
